PythonFreeCourse/lms

- lmsweb/models.py
- tests/conftest.py
- tests/test_models.py
and a sanity test for checking the tables.
> added comment and solution tables

- lmsweb/__init__.py
- lmsweb/models.py
- lmsweb/views.py
- tests/conftest.py
- tests/test_models.py
* Endpoint for most common comments, supporting specific exercises only
* Remove imports from `lms`
* Convert `ManyToManyField` into explicit ManyToMany, using an external table
* Login required for relevant endpoints
> Common comments endpoints

- lmsweb/models.py
- lmsweb/views.py
+ Add Role.is_manager + "managers_only" decorator
+ Use Flask's builtin "current_user" instead of session[...]
+ Minor code cleanup
> Managers_only and code cleanup

- lms/static/keyboard.js
> Stylize code, fix ninja mode autotester integration

- lms/lmsdb/models.py
- lms/lmsweb/views.py
- lms/static/my.css
- lms/templates/view.html
> Percentage progress in solution exercise

- lms/lmsdb/models.py
- lms/lmsweb/views.py
- lms/models/notifications.py
- lms/static/my.css
- lms/static/my.js
- lms/templates/navbar.html
- Enable reading notification
- Mark all related objects as read
- Add Javascript counter to indicate number of unreads
> feat: Add notification counter (#86)

- .gitignore
- README.md
- devops/dev_bootstrap.sh
- lms/lmsdb/database_config.py
Local debugging setup (FE + SQLite)
Doesn't include a full-setup with debugging capabilities.
> Development bootstrap script

- lms/lmsdb/models.py
- lms/lmsweb/views.py
- lms/models/solutions.py
- lms/static/comments.js
- lms/static/grader.js
- lms/static/hawcons.css
- lms/static/my.css
- lms/static/prism.css
- lms/templates/exercises.html
- lms/templates/filetree.html
- Updated the style of the add comments
- Changed the location of the tags
- Made them disappear while the mouse not pointing on the line
- Updated the style of the copy button
- Added how many total comments tag near each exercise
> feat: Update add comments tags

- .flake8
Handle some errors detected by flake8.
Setting to ignore missing whitespace error in sample code.
> Ignore missing whitespace error in sample code

- .flake8
- README.md
Updating readme - related to issue #39 
TBD -
> Issue #39 - update readme - phase 1

- lms/static/comments.js
> fix: comments.js bad linebreaks.

- lms/static/keyboard.js
- Changed the comments to be updated to the file id instead of the solution id
> feat: Fix vim comments

- lms/lmsweb/translations/en/LC_MESSAGES/messages.po
- lms/lmsweb/views.py
- lms/static/my.css
- lms/static/my.js
- lms/templates/view.html
- Added a toolbar in the top of the code view
- Moved the copy, download and share buttons to the toolbar
- Added the number of lines counter in the left corner
> feat: Add toolbar to Solution page

- lms/static/grader.js
- Comments which deleted are not going to be appeared after showing the popover again and again
> fix: Deletion of comments

- lms/static/my.js
- lms/templates/upload.html
- Now post upload message of misses and matches will appear only if there are misses or matches
> fix: Post upload message

- lms/extractors/base.py
- lms/extractors/notebook.py
- lms/extractors/textfile.py
- lms/tests/samples/upload-1-2.ipynb
- lms/tests/test_extractor.py
- lms/utils/files.py
- Fixed the type getter function
- Fixed unittest of notebooks extractor
> feat: Allow html python notebook

- lms/lmsweb/admin.py
- lms/lmsweb/redirections.py
- lms/lmsweb/views.py
- lms/models/comments.py
- Seperated constant and functions to external files
- Moved the flask admin to another file
> feat: Seperate `views` logic

- lms/lmsdb/models.py
- lms/models/upload.py
- lms/tests/test_solutions.py
Compare the content of a re-uploded solution only with the user's latest uploaded solution of that specific exercise.
> Fix Bug Preventing Reupload

- lms/lmsdb/models.py
- lms/models/upload.py
- lms/tests/test_solutions.py
Reverts PythonFreeCourse/lms#229
Currently causing crush:
```
peewee.ProgrammingError: column "t1.submission_timestamp" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...Y "t1"."solver_id", "t1"."exercise_id" HAVING (((("t1"."subm...
```
> fix: Revert "Fix Bug Preventing Reupload"

- README.md
- requirements.txt
- Added to the requirements the Babel
- Changed the order of the installation
> fix: Babel compiling

- devops/upgrade.sh
- Added a script in the upgrade shell file to check that there is enough free space in the partition (200MB)
> feat: Add diskspace checkups during upgrades

- lms/lmsdb/models.py
- lms/lmstests/public/identical_tests/services.py
- lms/lmstests/public/linters/services.py
- lms/lmstests/public/unittests/services.py
- lms/lmsweb/__init__.py
- lms/lmsweb/admin.py
- lms/lmsweb/redirections.py
- lms/lmsweb/tools/registration.py
- lms/lmsweb/views.py
- lms/models/comments.py
- lms/models/errors.py
- lms/models/share_link.py
- lms/models/solutions.py
- tests/conftest.py
- tests/test_download_file.py
- tests/test_solutions.py
- tests/test_users.py
- Moved comments logic out of views file into models/comments
- Changed fields from list type into a tuple
> feat: Move logic of view, download and comments out of views file

- lms/lmsdb/models.py
- lms/lmsweb/views.py
- lms/models/share_link.py
- tests/test_solutions.py
- Each time user enters a shared-link - it is written to the database as a SharedSolutionEntry
- Added a test
> feat: Add share statistics

- lms/lmsweb/views.py
- tests/conftest.py
- tests/test_flask_limiter.py
- tests/test_notes.py
- tests/test_solutions.py
- Limited shared links to 5 entries per minute
- Added a test
- Added a test to unknown act of comments
- Added test coverage for shared links
> feat: Limit shared links

- requirements.txt
reverted changes for urlib3 version, dependabot suggested an incorrect update
https://github.com/dependabot/dependabot-core/issues/3243#issue-824020572
an already issue at dependabot
closes #290
> chore: urllib3 version downgrade 

- lms/static/checker.js
- lms/static/comments.js
- lms/static/grader.js
- lms/templates/view.html
- Moved method to a new js file that only managers can use
- Now users can also comment, depends on config settings of USERS_COMMENTS
> fix: User comments
